### ISSUE TITLE
Support for filtering `null` columns

### ISSUE THREAD

**Issue by taylorbrooks** [robconery/moebius#35]
I'm trying to do a query that would result in SQL like this:

``` sql
select * from emails where deleted_at IS NULL;
# or
select * from emails where deleted_at IS NOT NULL;
```

``` elixir
db(:emails)
|> filter(:deleted_at, "IS NULL")
|> all
```

Results in:

``` elixir
** (FunctionClauseError) no function clause matching in Postgrex.Extensions.Binary.encode_timestamp/1
    (postgrex) lib/postgrex/extensions/binary.ex:241: Postgrex.Extensions.Binary.encode_timestamp("IS NULL")
    (postgrex) lib/postgrex/protocol.ex:299: anonymous fn/2 in Postgrex.Protocol.encode_params/1
      (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
      (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
      (elixir) lib/enum.ex:1043: Enum.map/2
    (postgrex) lib/postgrex/protocol.ex:294: Postgrex.Protocol.encode_params/1
    (postgrex) lib/postgrex/protocol.ex:264: Postgrex.Protocol.send_params/2
    (postgrex) lib/postgrex/protocol.ex:136: Postgrex.Protocol.message/3
```

**Comment by robconery** [comment]
Probably the easiest way is to do this:

``` ex
db(:emails)
|> filter("deleted_at IS NULL")
|> all
```

Although what you wrote above _should work_. I'm a bit puzzled because we had a filter method in there where you could:

``` ex
db(:emails)
|> filter(:id, ">", 100)
|> all
```

... which should allow you to do this. Anyway the query here should work for you (for now) - I''ll leave this open to work on for 1.0.9. Cheers.

**Comment by taylorbrooks** [comment]
I get an `unidentified func filter/4` for your 2nd example.

The first example works, but not when I pipe through `filter()` a second time:

``` elixir
iex(36)> db(:emails) |> filter(user_id: 16) |> count
919

iex(37)> db(:emails) |> filter(user_id: 16) |> filter("deleted_at IS NULL") |> count
36081

## what the queries look like: 

iex(38)> db(:emails) |> filter(user_id: 16)                                         
%Moebius.QueryCommand{columns: nil, error: nil, group_by: nil, join: [""],
 limit: "", offset: "", order: "", params: [16], pid: nil, sql: nil,
 table_name: "emails", type: :select, vals: nil, where: " where user_id = $1",
 where_columns: [:user_id]}

iex(39)> db(:emails) |> filter(user_id: 16) |> filter("deleted_at IS NULL")         
%Moebius.QueryCommand{columns: nil, error: nil, group_by: nil, join: [""],
 limit: "", offset: "", order: "", params: [], pid: nil, sql: nil,
 table_name: "emails", type: :select, vals: nil,
 where: " where deleted_at IS NULL", where_columns: [:user_id]}
```

So it appears the 2nd pass through `filter()` is destructive.

**Comment by nurugger07** [comment]
You can't pass through to filters now. This is something that I wanted to look at. @taylorbrooks We are doing it but updating :where in the map

—
Thanks,

Johnny

**Comment by nurugger07** [comment]
I guess I should look at this issue :)

**Comment by robconery** [comment]
The filter issue is fixed; null values (from OP) are handled with string pass. If I'm wrong on understanding this please reopen.
