### ISSUE TITLE
Db.save inside a transaction fails if DocumentQuery.searchable is specified before

### ISSUE THREAD

**Issue by amagdas** [robconery/moebius#53]
The following test fails:

``` elixir
test "documents save within a transaction" do
    res = transaction fn(tx) ->
      Moebius.DocumentQuery.db(:monkies) |> Moebius.DocumentQuery.searchable([:name]) |> TestDb.save(%{name: "Mike"}, tx)
    end
    case res do
      {:error, _err} -> flunk "No errors here!"
      res -> assert res
    end
 end
```

**Comment by robconery** [comment]
The error code etc would be helpful.

**Comment by amagdas** [comment]
```
1) test documents save within a transaction (Moebius.TransactionTest)
     test/moebius/transaction_test.exs:52
     ** (exit) exited in: :gen_server.call(TestDb, {:checkout, #Reference<0.0.3.366>, true, 5000}, 5000)
         ** (EXIT) time out
     stacktrace:
       (db_connection) lib/db_connection/connection.ex:43: DBConnection.Connection.checkout/2
       (db_connection) lib/db_connection.ex:811: DBConnection.checkout/2
       (db_connection) lib/db_connection.ex:717: DBConnection.run/3
       (db_connection) lib/db_connection.ex:957: DBConnection.run_meter/3
       (db_connection) lib/db_connection.ex:421: DBConnection.query/4
       (postgrex) lib/postgrex.ex:111: Postgrex.query/4
       (moebius) lib/moebius/database.ex:236: Moebius.Database.execute/1
       lib/moebius/database.ex:220: TestDb.update_search/2
       lib/moebius/database.ex:170: TestDb.handle_save_result/3
       lib/moebius/database.ex:134: TestDb.save/3
       test/moebius/transaction_test.exs:54: anonymous fn/1 in Moebius.TransactionTest.test documents save within a transaction/1
       (db_connection) lib/db_connection.ex:1079: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:766: DBConnection.transaction/3
       lib/moebius/database.ex:109: TestDb.transaction/1
       test/moebius/transaction_test.exs:53

```

**Comment by robconery** [comment]
Yep - I see it. A timeout is happening because the transaction is still open, and we're running a separate query to update the search columns _without_ that transaction being passed along. It looks like we need an additional function head here:

https://github.com/robconery/moebius/blob/master/lib/moebius/database.ex#L170

To handle the case when a transaction pid (`conn`) is passed in. I don't have time to get to this, but if you wanted to PR that would be super super helpful :).

**Comment by amagdas** [comment]
Sure, will do.
